//
//  BespokeAnimations.swift
//  InspireCreativityApp
//
//  Central registration for the bespoke catalog animations. Each entry maps a
//  catalog id to two preview builders:
//   • grid        — the self-driving demo loop shown in grid tiles (demo: true)
//   • interactive — the real, finger-driven component shown in Detail (demo: false)
//
//  Integration appends one `.init(...)` line per animation. The per-animation
//  VIEW lives in its own file under Animations/Catalog/<Category>/.
//

import SwiftUI

struct BespokeAnimation {
    let id: String
    let grid: PreviewBuilder
    let interactive: PreviewBuilder
}

enum BespokeAnimations {

    static let all: [BespokeAnimation] = [
        .init(id: "ges-rubberband-sheet-morph",
              grid: { AnyView(RubberBandSheetMorphView(demo: true)) },
              interactive: { AnyView(RubberBandSheetMorphView(demo: false)) }),
        .init(id: "tx-shatter-glass",
              grid: { AnyView(GlassShatterSettleView(demo: true)) },
              interactive: { AnyView(GlassShatterSettleView(demo: false)) }),
        .init(id: "mtl-heat-mirage",
              grid: { AnyView(HeatMirageView(demo: true)) },
              interactive: { AnyView(HeatMirageView(demo: false)) }),
                .init(id: "ges-accordion-fold-list",
              grid: { AnyView(AccordionFoldListView(demo: true)) },
              interactive: { AnyView(AccordionFoldListView(demo: false)) }),
        .init(id: "ges-crumple-dismiss",
              grid: { AnyView(CrumpleDismissView(demo: true)) },
              interactive: { AnyView(CrumpleDismissView(demo: false)) }),
        .init(id: "ges-drag-elastic-grid-warp",
              grid: { AnyView(DragElasticGridWarpView(demo: true)) },
              interactive: { AnyView(DragElasticGridWarpView(demo: false)) }),
        .init(id: "ges-drag-liquid-fill-tilt",
              grid: { AnyView(DragLiquidFillTiltView(demo: true)) },
              interactive: { AnyView(DragLiquidFillTiltView(demo: false)) }),
        .init(id: "ges-drag-reorder-spring",
              grid: { AnyView(DragReorderSpringView(demo: true)) },
              interactive: { AnyView(DragReorderSpringView(demo: false)) }),
        .init(id: "ges-drag-rope-bridge",
              grid: { AnyView(DragRopeBridgeView(demo: true)) },
              interactive: { AnyView(DragRopeBridgeView(demo: false)) }),
        .init(id: "ges-drag-spring-net",
              grid: { AnyView(DragSpringNetView(demo: true)) },
              interactive: { AnyView(DragSpringNetView(demo: false)) }),
        .init(id: "ges-edge-swipe-page-curl",
              grid: { AnyView(EdgeSwipePageCurlView(demo: true)) },
              interactive: { AnyView(EdgeSwipePageCurlView(demo: false)) }),
        .init(id: "mi-bubble-wrap-pop",
              grid: { AnyView(BubbleWrapPopView(demo: true)) },
              interactive: { AnyView(BubbleWrapPopView(demo: false)) }),
        .init(id: "mi-copy-shred",
              grid: { AnyView(CopyShredView(demo: true)) },
              interactive: { AnyView(CopyShredView(demo: false)) }),
        .init(id: "mi-copy-vanish",
              grid: { AnyView(CopyVanishView(demo: true)) },
              interactive: { AnyView(CopyVanishView(demo: false)) }),
        .init(id: "btn-accordion-stretch",
              grid: { AnyView(AccordionStretchView(demo: true)) },
              interactive: { AnyView(AccordionStretchView(demo: false)) }),
        .init(id: "btn-blinds-reveal",
              grid: { AnyView(BlindsRevealView(demo: true)) },
              interactive: { AnyView(BlindsRevealView(demo: false)) }),
        .init(id: "tr-clock-pie-wipe",
              grid: { AnyView(ClockPieWipeView(demo: true)) },
              interactive: { AnyView(ClockPieWipeView(demo: false)) }),
        .init(id: "tr-column-slat-slide",
              grid: { AnyView(ColumnSlatSlideView(demo: true)) },
              interactive: { AnyView(ColumnSlatSlideView(demo: false)) }),
        .init(id: "tx-confetti-letters",
              grid: { AnyView(ConfettiLettersView(demo: true)) },
              interactive: { AnyView(ConfettiLettersView(demo: false)) }),
        .init(id: "ld-bouncing-payload",
              grid: { AnyView(BouncingPayloadView(demo: true)) },
              interactive: { AnyView(BouncingPayloadView(demo: false)) }),
        .init(id: "nav-arc-fan-menu",
              grid: { AnyView(ArcFanMenuView(demo: true)) },
              interactive: { AnyView(ArcFanMenuView(demo: false)) }),
        .init(id: "ges-fling-paper-plane",
              grid: { AnyView(FlingPaperPlaneView(demo: true)) },
              interactive: { AnyView(FlingPaperPlaneView(demo: false)) }),
        .init(id: "ges-fling-pinball-bumpers",
              grid: { AnyView(FlingPinballBumpersView(demo: true)) },
              interactive: { AnyView(FlingPinballBumpersView(demo: false)) }),
        .init(id: "ges-fling-spinner-coast",
              grid: { AnyView(FlingSpinnerCoastView(demo: true)) },
              interactive: { AnyView(FlingSpinnerCoastView(demo: false)) }),
        .init(id: "ges-gravity-bin-toss",
              grid: { AnyView(GravityBinTossView(demo: true)) },
              interactive: { AnyView(GravityBinTossView(demo: false)) }),
        .init(id: "ges-hold-charge-burst",
              grid: { AnyView(HoldChargeBurstView(demo: true)) },
              interactive: { AnyView(HoldChargeBurstView(demo: false)) }),
        .init(id: "ges-hold-drag-slingshot-aim",
              grid: { AnyView(HoldDragSlingshotAimView(demo: true)) },
              interactive: { AnyView(HoldDragSlingshotAimView(demo: false)) }),
        .init(id: "ges-inertial-marble-throw",
              grid: { AnyView(InertialMarbleThrowView(demo: true)) },
              interactive: { AnyView(InertialMarbleThrowView(demo: false)) }),
        .init(id: "ges-jelly-drag-blob",
              grid: { AnyView(JellyDragBlobView(demo: true)) },
              interactive: { AnyView(JellyDragBlobView(demo: false)) }),
        .init(id: "ges-long-press-melt",
              grid: { AnyView(LongPressMeltView(demo: true)) },
              interactive: { AnyView(LongPressMeltView(demo: false)) }),
        .init(id: "ges-magnetic-cursor-ferrofluid",
              grid: { AnyView(MagneticCursorFerrofluidView(demo: true)) },
              interactive: { AnyView(MagneticCursorFerrofluidView(demo: false)) }),
        .init(id: "ges-peel-away-card",
              grid: { AnyView(PeelAwayCardView(demo: true)) },
              interactive: { AnyView(PeelAwayCardView(demo: false)) }),
        .init(id: "ges-pinch-collapse-grid",
              grid: { AnyView(PinchCollapseGridView(demo: true)) },
              interactive: { AnyView(PinchCollapseGridView(demo: false)) }),
        .init(id: "ges-pinch-focus-depth",
              grid: { AnyView(PinchFocusDepthView(demo: true)) },
              interactive: { AnyView(PinchFocusDepthView(demo: false)) }),
        .init(id: "ges-pinch-origami-crane",
              grid: { AnyView(PinchOrigamiCraneView(demo: true)) },
              interactive: { AnyView(PinchOrigamiCraneView(demo: false)) }),
        .init(id: "ges-pinch-zoom-clamp-frame",
              grid: { AnyView(PinchZoomClampFrameView(demo: true)) },
              interactive: { AnyView(PinchZoomClampFrameView(demo: false)) }),
        .init(id: "ges-rotate-clock-rewind",
              grid: { AnyView(RotateClockRewindView(demo: true)) },
              interactive: { AnyView(RotateClockRewindView(demo: false)) }),
        .init(id: "ges-rotate-combination-lock",
              grid: { AnyView(RotateCombinationLockView(demo: true)) },
              interactive: { AnyView(RotateCombinationLockView(demo: false)) }),
        .init(id: "ges-rotate-dial-knob",
              grid: { AnyView(RotateDialKnobView(demo: true)) },
              interactive: { AnyView(RotateDialKnobView(demo: false)) }),
        .init(id: "ges-rotate-gear-train",
              grid: { AnyView(RotateGearTrainView(demo: true)) },
              interactive: { AnyView(RotateGearTrainView(demo: false)) }),
        .init(id: "ges-pull-to-trigger-bow",
              grid: { AnyView(PullToTriggerBowView(demo: true)) },
              interactive: { AnyView(PullToTriggerBowView(demo: false)) }),
        .init(id: "ges-rotate-vinyl-scrub",
              grid: { AnyView(RotateVinylScrubView(demo: true)) },
              interactive: { AnyView(RotateVinylScrubView(demo: false)) }),
        .init(id: "ges-swipe-curtain-part",
              grid: { AnyView(SwipeCurtainPartView(demo: true)) },
              interactive: { AnyView(SwipeCurtainPartView(demo: false)) }),
        .init(id: "ges-swipe-domino-cascade",
              grid: { AnyView(SwipeDominoCascadeView(demo: true)) },
              interactive: { AnyView(SwipeDominoCascadeView(demo: false)) }),
        .init(id: "ges-swipe-elastic-reveal",
              grid: { AnyView(SwipeElasticRevealView(demo: true)) },
              interactive: { AnyView(SwipeElasticRevealView(demo: false)) }),
        .init(id: "ges-swipe-stack-shuffle",
              grid: { AnyView(SwipeStackShuffleView(demo: true)) },
              interactive: { AnyView(SwipeStackShuffleView(demo: false)) }),
        .init(id: "ges-swipe-stamp-impress",
              grid: { AnyView(SwipeStampImpressView(demo: true)) },
              interactive: { AnyView(SwipeStampImpressView(demo: false)) }),
        .init(id: "ges-throw-and-catch-orbit",
              grid: { AnyView(ThrowAndCatchOrbitView(demo: true)) },
              interactive: { AnyView(ThrowAndCatchOrbitView(demo: false)) }),
        .init(id: "ges-two-finger-shear",
              grid: { AnyView(TwoFingerShearView(demo: true)) },
              interactive: { AnyView(TwoFingerShearView(demo: false)) }),
        .init(id: "ges-two-finger-tear-seam",
              grid: { AnyView(TwoFingerTearSeamView(demo: true)) },
              interactive: { AnyView(TwoFingerTearSeamView(demo: false)) }),
        .init(id: "ges-zipper-unzip",
              grid: { AnyView(ZipperUnzipView(demo: true)) },
              interactive: { AnyView(ZipperUnzipView(demo: false)) }),
        .init(id: "mi-day-night-toggle",
              grid: { AnyView(DayNightToggleView(demo: true)) },
              interactive: { AnyView(DayNightToggleView(demo: false)) }),
        .init(id: "mi-dogear-bookmark",
              grid: { AnyView(DogearBookmarkView(demo: true)) },
              interactive: { AnyView(DogearBookmarkView(demo: false)) }),
        .init(id: "mi-elastic-segmented",
              grid: { AnyView(ElasticSegmentedView(demo: true)) },
              interactive: { AnyView(ElasticSegmentedView(demo: false)) }),
        .init(id: "mi-emoji-fountain",
              grid: { AnyView(EmojiFountainView(demo: true)) },
              interactive: { AnyView(EmojiFountainView(demo: false)) }),
        .init(id: "mi-favorite-fold",
              grid: { AnyView(FavoriteFoldView(demo: true)) },
              interactive: { AnyView(FavoriteFoldView(demo: false)) }),
        .init(id: "mi-jelly-count-badge",
              grid: { AnyView(JellyCountBadgeView(demo: true)) },
              interactive: { AnyView(JellyCountBadgeView(demo: false)) }),
        .init(id: "mi-knurled-stepper",
              grid: { AnyView(KnurledStepperView(demo: true)) },
              interactive: { AnyView(KnurledStepperView(demo: false)) }),
        .init(id: "mi-magnetic-radio-snap",
              grid: { AnyView(MagneticRadioSnapView(demo: true)) },
              interactive: { AnyView(MagneticRadioSnapView(demo: false)) }),
        .init(id: "ges-tear-receipt",
              grid: { AnyView(TearReceiptView(demo: true)) },
              interactive: { AnyView(TearReceiptView(demo: false)) }),
        .init(id: "mi-magnetic-snap-toggle",
              grid: { AnyView(MagneticSnapToggleView(demo: true)) },
              interactive: { AnyView(MagneticSnapToggleView(demo: false)) }),
        .init(id: "mi-mood-morph-rating",
              grid: { AnyView(MoodMorphRatingView(demo: true)) },
              interactive: { AnyView(MoodMorphRatingView(demo: false)) }),
        .init(id: "mi-mute-morph",
              grid: { AnyView(MuteMorphView(demo: true)) },
              interactive: { AnyView(MuteMorphView(demo: false)) }),
        .init(id: "mi-orbit-badge",
              grid: { AnyView(OrbitBadgeView(demo: true)) },
              interactive: { AnyView(OrbitBadgeView(demo: false)) }),
        .init(id: "mi-otp-cascade",
              grid: { AnyView(OtpCascadeView(demo: true)) },
              interactive: { AnyView(OtpCascadeView(demo: false)) }),
        .init(id: "mi-particle-assemble-check",
              grid: { AnyView(ParticleAssembleCheckView(demo: true)) },
              interactive: { AnyView(ParticleAssembleCheckView(demo: false)) }),
        .init(id: "mi-password-reveal",
              grid: { AnyView(PasswordRevealView(demo: true)) },
              interactive: { AnyView(PasswordRevealView(demo: false)) }),
        .init(id: "mi-pin-shake-success",
              grid: { AnyView(PinShakeSuccessView(demo: true)) },
              interactive: { AnyView(PinShakeSuccessView(demo: false)) }),
        .init(id: "mi-popcorn-emoji",
              grid: { AnyView(PopcornEmojiView(demo: true)) },
              interactive: { AnyView(PopcornEmojiView(demo: false)) }),
        .init(id: "mi-pressure-pop",
              grid: { AnyView(PressurePopView(demo: true)) },
              interactive: { AnyView(PressurePopView(demo: false)) }),
        .init(id: "mi-punchout-check",
              grid: { AnyView(PunchoutCheckView(demo: true)) },
              interactive: { AnyView(PunchoutCheckView(demo: false)) }),
        .init(id: "mi-radio-ink",
              grid: { AnyView(RadioInkView(demo: true)) },
              interactive: { AnyView(RadioInkView(demo: false)) }),
        .init(id: "mi-reaction-tray-roll",
              grid: { AnyView(ReactionTrayRollView(demo: true)) },
              interactive: { AnyView(ReactionTrayRollView(demo: false)) }),
        .init(id: "mi-ribbon-drop-bookmark",
              grid: { AnyView(RibbonDropBookmarkView(demo: true)) },
              interactive: { AnyView(RibbonDropBookmarkView(demo: false)) }),
        .init(id: "mi-rolodex-quantity",
              grid: { AnyView(RolodexQuantityView(demo: true)) },
              interactive: { AnyView(RolodexQuantityView(demo: false)) }),
        .init(id: "mi-scrubber-wave",
              grid: { AnyView(ScrubberWaveView(demo: true)) },
              interactive: { AnyView(ScrubberWaveView(demo: false)) }),
        .init(id: "mi-slide-to-confirm",
              grid: { AnyView(SlideToConfirmView(demo: true)) },
              interactive: { AnyView(SlideToConfirmView(demo: false)) }),
        .init(id: "mi-staggered-star-rating",
              grid: { AnyView(StaggeredStarRatingView(demo: true)) },
              interactive: { AnyView(StaggeredStarRatingView(demo: false)) }),
        .init(id: "mi-stretch-pill-switch",
              grid: { AnyView(StretchPillSwitchView(demo: true)) },
              interactive: { AnyView(StretchPillSwitchView(demo: false)) }),
        .init(id: "mi-swipe-reveal-trash",
              grid: { AnyView(SwipeRevealTrashView(demo: true)) },
              interactive: { AnyView(SwipeRevealTrashView(demo: false)) }),
        .init(id: "mi-tactile-counter-flip",
              grid: { AnyView(TactileCounterFlipView(demo: true)) },
              interactive: { AnyView(TactileCounterFlipView(demo: false)) }),
        .init(id: "mi-thumb-flip-like",
              grid: { AnyView(ThumbFlipLikeView(demo: true)) },
              interactive: { AnyView(ThumbFlipLikeView(demo: false)) }),
        .init(id: "mi-trace-checkmark",
              grid: { AnyView(TraceCheckmarkView(demo: true)) },
              interactive: { AnyView(TraceCheckmarkView(demo: false)) }),
        .init(id: "mi-volume-fluid",
              grid: { AnyView(VolumeFluidView(demo: true)) },
              interactive: { AnyView(VolumeFluidView(demo: false)) }),
        .init(id: "btn-breath-idle",
              grid: { AnyView(BreathIdleView(demo: true)) },
              interactive: { AnyView(BreathIdleView(demo: false)) }),
        .init(id: "btn-conveyor-load",
              grid: { AnyView(ConveyorLoadView(demo: true)) },
              interactive: { AnyView(ConveyorLoadView(demo: false)) }),
        .init(id: "btn-cube-roll",
              grid: { AnyView(CubeRollView(demo: true)) },
              interactive: { AnyView(CubeRollView(demo: false)) }),
        .init(id: "btn-domino-segment",
              grid: { AnyView(DominoSegmentView(demo: true)) },
              interactive: { AnyView(DominoSegmentView(demo: false)) }),
        .init(id: "btn-elastic-sling",
              grid: { AnyView(ElasticSlingView(demo: true)) },
              interactive: { AnyView(ElasticSlingView(demo: false)) }),
        .init(id: "btn-ferrofluid-spike",
              grid: { AnyView(FerrofluidSpikeView(demo: true)) },
              interactive: { AnyView(FerrofluidSpikeView(demo: false)) }),
        .init(id: "btn-flip-clock-toggle",
              grid: { AnyView(FlipClockToggleView(demo: true)) },
              interactive: { AnyView(FlipClockToggleView(demo: false)) }),
        .init(id: "btn-fuse-spark",
              grid: { AnyView(FuseSparkView(demo: true)) },
              interactive: { AnyView(FuseSparkView(demo: false)) }),
        .init(id: "btn-knob-detent",
              grid: { AnyView(KnobDetentView(demo: true)) },
              interactive: { AnyView(KnobDetentView(demo: false)) }),
        .init(id: "btn-gel-jiggle",
              grid: { AnyView(GelJiggleView(demo: true)) },
              interactive: { AnyView(GelJiggleView(demo: false)) }),
        .init(id: "btn-ink-bleed-toggle",
              grid: { AnyView(InkBleedToggleView(demo: true)) },
              interactive: { AnyView(InkBleedToggleView(demo: false)) }),
        .init(id: "btn-magnetic-snap",
              grid: { AnyView(MagneticSnapView(demo: true)) },
              interactive: { AnyView(MagneticSnapView(demo: false)) }),
        .init(id: "btn-mercury-fill",
              grid: { AnyView(MercuryFillView(demo: true)) },
              interactive: { AnyView(MercuryFillView(demo: false)) }),
        .init(id: "btn-origami-fold",
              grid: { AnyView(OrigamiFoldView(demo: true)) },
              interactive: { AnyView(OrigamiFoldView(demo: false)) }),
        .init(id: "btn-piston-pump",
              grid: { AnyView(PistonPumpView(demo: true)) },
              interactive: { AnyView(PistonPumpView(demo: false)) }),
        .init(id: "btn-sand-pour",
              grid: { AnyView(SandPourView(demo: true)) },
              interactive: { AnyView(SandPourView(demo: false)) }),
        .init(id: "btn-shatter-reform",
              grid: { AnyView(ShatterReformView(demo: true)) },
              interactive: { AnyView(ShatterReformView(demo: false)) }),
        .init(id: "btn-static-discharge",
              grid: { AnyView(StaticDischargeView(demo: true)) },
              interactive: { AnyView(StaticDischargeView(demo: false)) }),
        .init(id: "btn-stitch-thread",
              grid: { AnyView(StitchThreadView(demo: true)) },
              interactive: { AnyView(StitchThreadView(demo: false)) }),
        .init(id: "btn-tear-perforation",
              grid: { AnyView(TearPerforationView(demo: true)) },
              interactive: { AnyView(TearPerforationView(demo: false)) }),
        .init(id: "btn-thermal-press",
              grid: { AnyView(ThermalPressView(demo: true)) },
              interactive: { AnyView(ThermalPressView(demo: false)) }),
        .init(id: "btn-vault-dial",
              grid: { AnyView(VaultDialView(demo: true)) },
              interactive: { AnyView(VaultDialView(demo: false)) }),
        .init(id: "btn-zipper-confirm",
              grid: { AnyView(ZipperConfirmView(demo: true)) },
              interactive: { AnyView(ZipperConfirmView(demo: false)) }),
        .init(id: "tr-crumple-fade",
              grid: { AnyView(CrumpleFadeView(demo: true)) },
              interactive: { AnyView(CrumpleFadeView(demo: false)) }),
        .init(id: "tr-cube-tumble",
              grid: { AnyView(CubeTumbleView(demo: true)) },
              interactive: { AnyView(CubeTumbleView(demo: false)) }),
        .init(id: "tr-depth-stack-push",
              grid: { AnyView(DepthStackPushView(demo: true)) },
              interactive: { AnyView(DepthStackPushView(demo: false)) }),
        .init(id: "tr-fan-deck",
              grid: { AnyView(FanDeckView(demo: true)) },
              interactive: { AnyView(FanDeckView(demo: false)) }),
        .init(id: "tr-flip-book",
              grid: { AnyView(FlipBookView(demo: true)) },
              interactive: { AnyView(FlipBookView(demo: false)) }),
        .init(id: "tr-drawer-cascade",
              grid: { AnyView(DrawerCascadeView(demo: true)) },
              interactive: { AnyView(DrawerCascadeView(demo: false)) }),
        .init(id: "tr-fold-accordion",
              grid: { AnyView(FoldAccordionView(demo: true)) },
              interactive: { AnyView(FoldAccordionView(demo: false)) }),
        .init(id: "tr-genie-warp",
              grid: { AnyView(GenieWarpView(demo: true)) },
              interactive: { AnyView(GenieWarpView(demo: false)) }),
        .init(id: "tr-glass-shatter",
              grid: { AnyView(GlassShatterView(demo: true)) },
              interactive: { AnyView(GlassShatterView(demo: false)) }),
        .init(id: "tr-hero-zoom-scatter",
              grid: { AnyView(HeroZoomScatterView(demo: true)) },
              interactive: { AnyView(HeroZoomScatterView(demo: false)) }),
        .init(id: "tr-iris-shutter",
              grid: { AnyView(IrisShutterView(demo: true)) },
              interactive: { AnyView(IrisShutterView(demo: false)) }),
        .init(id: "tr-liquid-drip",
              grid: { AnyView(LiquidDripView(demo: true)) },
              interactive: { AnyView(LiquidDripView(demo: false)) }),
        .init(id: "tr-magnetic-swap",
              grid: { AnyView(MagneticSwapView(demo: true)) },
              interactive: { AnyView(MagneticSwapView(demo: false)) }),
        .init(id: "tr-metaball-merge",
              grid: { AnyView(MetaballMergeView(demo: true)) },
              interactive: { AnyView(MetaballMergeView(demo: false)) }),
        .init(id: "tr-mosaic-flip",
              grid: { AnyView(MosaicFlipView(demo: true)) },
              interactive: { AnyView(MosaicFlipView(demo: false)) }),
        .init(id: "tr-origami-unfold",
              grid: { AnyView(OrigamiUnfoldView(demo: true)) },
              interactive: { AnyView(OrigamiUnfoldView(demo: false)) }),
        .init(id: "tr-page-peel",
              grid: { AnyView(PagePeelView(demo: true)) },
              interactive: { AnyView(PagePeelView(demo: false)) }),
        .init(id: "tr-spotlight-sweep",
              grid: { AnyView(SpotlightSweepView(demo: true)) },
              interactive: { AnyView(SpotlightSweepView(demo: false)) }),
        .init(id: "tr-taffy-bridge",
              grid: { AnyView(TaffyBridgeView(demo: true)) },
              interactive: { AnyView(TaffyBridgeView(demo: false)) }),
        .init(id: "tr-theater-curtain",
              grid: { AnyView(TheaterCurtainView(demo: true)) },
              interactive: { AnyView(TheaterCurtainView(demo: false)) }),
        .init(id: "tr-venetian-blinds",
              grid: { AnyView(VenetianBlindsView(demo: true)) },
              interactive: { AnyView(VenetianBlindsView(demo: false)) }),
        .init(id: "tr-vortex-spiral",
              grid: { AnyView(VortexSpiralView(demo: true)) },
              interactive: { AnyView(VortexSpiralView(demo: false)) }),
        .init(id: "tr-zipper-unzip",
              grid: { AnyView(ZipperUnzipTransitionView(demo: true)) },
              interactive: { AnyView(ZipperUnzipTransitionView(demo: false)) }),
        .init(id: "tx-decode-matrix",
              grid: { AnyView(DecodeMatrixView(demo: true)) },
              interactive: { AnyView(DecodeMatrixView(demo: false)) }),
        .init(id: "tx-elastic-pop",
              grid: { AnyView(ElasticPopView(demo: true)) },
              interactive: { AnyView(ElasticPopView(demo: false)) }),
        .init(id: "tx-elastic-rope",
              grid: { AnyView(ElasticRopeView(demo: true)) },
              interactive: { AnyView(ElasticRopeView(demo: false)) }),
        .init(id: "tx-fold-origami",
              grid: { AnyView(FoldOrigamiView(demo: true)) },
              interactive: { AnyView(FoldOrigamiView(demo: false)) }),
        .init(id: "tx-gooey-merge",
              grid: { AnyView(GooeyMergeView(demo: true)) },
              interactive: { AnyView(GooeyMergeView(demo: false)) }),
        .init(id: "tx-gradient-flow",
              grid: { AnyView(GradientFlowView(demo: true)) },
              interactive: { AnyView(GradientFlowView(demo: false)) }),
        .init(id: "tx-handwriting",
              grid: { AnyView(HandwritingView(demo: true)) },
              interactive: { AnyView(HandwritingView(demo: false)) }),
        .init(id: "tx-liquid-fill",
              grid: { AnyView(LiquidFillView(demo: true)) },
              interactive: { AnyView(LiquidFillView(demo: false)) }),
        .init(id: "tx-magnetic-poetry",
              grid: { AnyView(MagneticPoetryView(demo: true)) },
              interactive: { AnyView(MagneticPoetryView(demo: false)) }),
        .init(id: "tx-marquee-3d",
              grid: { AnyView(Marquee3dView(demo: true)) },
              interactive: { AnyView(Marquee3dView(demo: false)) }),
        .init(id: "tx-neon-flicker",
              grid: { AnyView(NeonFlickerView(demo: true)) },
              interactive: { AnyView(NeonFlickerView(demo: false)) }),
        .init(id: "tx-odometer-blur",
              grid: { AnyView(OdometerBlurView(demo: true)) },
              interactive: { AnyView(OdometerBlurView(demo: false)) }),
        .init(id: "tx-ransom-note",
              grid: { AnyView(RansomNoteView(demo: true)) },
              interactive: { AnyView(RansomNoteView(demo: false)) }),
        .init(id: "tx-split-flap",
              grid: { AnyView(SplitFlapView(demo: true)) },
              interactive: { AnyView(SplitFlapView(demo: false)) }),
        .init(id: "tx-spotlight-sweep",
              grid: { AnyView(SpotlightSweepTextView(demo: true)) },
              interactive: { AnyView(SpotlightSweepTextView(demo: false)) }),
        .init(id: "tx-stamp-ink",
              grid: { AnyView(StampInkView(demo: true)) },
              interactive: { AnyView(StampInkView(demo: false)) }),
        .init(id: "tx-typewriter-cursor",
              grid: { AnyView(TypewriterCursorView(demo: true)) },
              interactive: { AnyView(TypewriterCursorView(demo: false)) }),
        .init(id: "tx-weight-breathe",
              grid: { AnyView(WeightBreatheView(demo: true)) },
              interactive: { AnyView(WeightBreatheView(demo: false)) }),
        .init(id: "ld-coin-flip-stack",
              grid: { AnyView(CoinFlipStackView(demo: true)) },
              interactive: { AnyView(CoinFlipStackView(demo: false)) }),
        .init(id: "ld-comet-trail-orbit",
              grid: { AnyView(CometTrailOrbitView(demo: true)) },
              interactive: { AnyView(CometTrailOrbitView(demo: false)) }),
        .init(id: "ld-dna-helix",
              grid: { AnyView(DnaHelixView(demo: true)) },
              interactive: { AnyView(DnaHelixView(demo: false)) }),
        .init(id: "ld-dot-grid-wave",
              grid: { AnyView(DotGridWaveView(demo: true)) },
              interactive: { AnyView(DotGridWaveView(demo: false)) }),
        .init(id: "ld-flip-clock-progress",
              grid: { AnyView(FlipClockProgressView(demo: true)) },
              interactive: { AnyView(FlipClockProgressView(demo: false)) }),
        .init(id: "ld-folding-origami",
              grid: { AnyView(FoldingOrigamiView(demo: true)) },
              interactive: { AnyView(FoldingOrigamiView(demo: false)) }),
        .init(id: "ld-gear-train",
              grid: { AnyView(GearTrainView(demo: true)) },
              interactive: { AnyView(GearTrainView(demo: false)) }),
        .init(id: "ld-infinity-flow",
              grid: { AnyView(InfinityFlowView(demo: true)) },
              interactive: { AnyView(InfinityFlowView(demo: false)) }),
        .init(id: "ld-knit-braid",
              grid: { AnyView(KnitBraidView(demo: true)) },
              interactive: { AnyView(KnitBraidView(demo: false)) }),
        .init(id: "ld-liquid-flask-fill",
              grid: { AnyView(LiquidFlaskFillView(demo: true)) },
              interactive: { AnyView(LiquidFlaskFillView(demo: false)) }),
        .init(id: "ld-magnetic-filings",
              grid: { AnyView(MagneticFilingsView(demo: true)) },
              interactive: { AnyView(MagneticFilingsView(demo: false)) }),
        .init(id: "ld-metaball-orbit",
              grid: { AnyView(MetaballOrbitView(demo: true)) },
              interactive: { AnyView(MetaballOrbitView(demo: false)) }),
        .init(id: "ld-morse-pulse",
              grid: { AnyView(MorsePulseView(demo: true)) },
              interactive: { AnyView(MorsePulseView(demo: false)) }),
        .init(id: "ld-orbital-electrons",
              grid: { AnyView(OrbitalElectronsView(demo: true)) },
              interactive: { AnyView(OrbitalElectronsView(demo: false)) }),
        .init(id: "ld-particle-assemble-logo",
              grid: { AnyView(ParticleAssembleLogoView(demo: true)) },
              interactive: { AnyView(ParticleAssembleLogoView(demo: false)) }),
        .init(id: "ld-pendulum-newton",
              grid: { AnyView(PendulumNewtonView(demo: true)) },
              interactive: { AnyView(PendulumNewtonView(demo: false)) }),
        .init(id: "ld-radar-sweep",
              grid: { AnyView(RadarSweepView(demo: true)) },
              interactive: { AnyView(RadarSweepView(demo: false)) }),
        .init(id: "ld-sand-hourglass",
              grid: { AnyView(SandHourglassView(demo: true)) },
              interactive: { AnyView(SandHourglassView(demo: false)) }),
        .init(id: "ld-segment-relay",
              grid: { AnyView(SegmentRelayView(demo: true)) },
              interactive: { AnyView(SegmentRelayView(demo: false)) }),
        .init(id: "nav-collapsing-chevron-crumbs",
              grid: { AnyView(CollapsingChevronCrumbsView(demo: true)) },
              interactive: { AnyView(CollapsingChevronCrumbsView(demo: false)) }),
        .init(id: "nav-comet-trail-crumbs",
              grid: { AnyView(CometTrailCrumbsView(demo: true)) },
              interactive: { AnyView(CometTrailCrumbsView(demo: false)) }),
        .init(id: "nav-concertina-sidebar",
              grid: { AnyView(ConcertinaSidebarView(demo: true)) },
              interactive: { AnyView(ConcertinaSidebarView(demo: false)) }),
        .init(id: "nav-flipboard-segment",
              grid: { AnyView(FlipboardSegmentView(demo: true)) },
              interactive: { AnyView(FlipboardSegmentView(demo: false)) }),
        .init(id: "nav-genie-magnify-dock",
              grid: { AnyView(GenieMagnifyDockView(demo: true)) },
              interactive: { AnyView(GenieMagnifyDockView(demo: false)) }),
        .init(id: "nav-inkbleed-segment",
              grid: { AnyView(InkbleedSegmentView(demo: true)) },
              interactive: { AnyView(InkbleedSegmentView(demo: false)) }),
        .init(id: "nav-magnetic-grab-drawer",
              grid: { AnyView(MagneticGrabDrawerView(demo: true)) },
              interactive: { AnyView(MagneticGrabDrawerView(demo: false)) }),
        .init(id: "nav-magnetic-snap-dock",
              grid: { AnyView(MagneticSnapDockView(demo: true)) },
              interactive: { AnyView(MagneticSnapDockView(demo: false)) }),
        .init(id: "nav-orbital-satellite-menu",
              grid: { AnyView(OrbitalSatelliteMenuView(demo: true)) },
              interactive: { AnyView(OrbitalSatelliteMenuView(demo: false)) }),
        .init(id: "nav-origami-fold-tabs",
              grid: { AnyView(OrigamiFoldTabsView(demo: true)) },
              interactive: { AnyView(OrigamiFoldTabsView(demo: false)) }),
        .init(id: "nav-pagecurl-drawer",
              grid: { AnyView(PagecurlDrawerView(demo: true)) },
              interactive: { AnyView(PagecurlDrawerView(demo: false)) }),
        .init(id: "nav-parallax-deck-tabs",
              grid: { AnyView(ParallaxDeckTabsView(demo: true)) },
              interactive: { AnyView(ParallaxDeckTabsView(demo: false)) }),
        .init(id: "nav-rolling-bead-tabs",
              grid: { AnyView(RollingBeadTabsView(demo: true)) },
              interactive: { AnyView(RollingBeadTabsView(demo: false)) }),
        .init(id: "ob-color-bleed",
              grid: { AnyView(ColorBleedView(demo: true)) },
              interactive: { AnyView(ColorBleedView(demo: false)) }),
        .init(id: "ob-constellation-hero",
              grid: { AnyView(ConstellationHeroView(demo: true)) },
              interactive: { AnyView(ConstellationHeroView(demo: false)) }),
        .init(id: "ob-depth-diorama",
              grid: { AnyView(DepthDioramaView(demo: true)) },
              interactive: { AnyView(DepthDioramaView(demo: false)) }),
        .init(id: "ob-ferrofluid-dots",
              grid: { AnyView(FerrofluidDotsView(demo: true)) },
              interactive: { AnyView(FerrofluidDotsView(demo: false)) }),
        .init(id: "ob-odometer-dots",
              grid: { AnyView(OdometerDotsView(demo: true)) },
              interactive: { AnyView(OdometerDotsView(demo: false)) }),
        .init(id: "ob-origami-hero",
              grid: { AnyView(OrigamiHeroView(demo: true)) },
              interactive: { AnyView(OrigamiHeroView(demo: false)) }),
        .init(id: "ob-paper-popup",
              grid: { AnyView(PaperPopupView(demo: true)) },
              interactive: { AnyView(PaperPopupView(demo: false)) }),
        .init(id: "ob-paper-tear",
              grid: { AnyView(PaperTearView(demo: true)) },
              interactive: { AnyView(PaperTearView(demo: false)) }),
        .init(id: "ob-permission-bell",
              grid: { AnyView(PermissionBellView(demo: true)) },
              interactive: { AnyView(PermissionBellView(demo: false)) }),
        .init(id: "ob-radar-lock",
              grid: { AnyView(RadarLockView(demo: true)) },
              interactive: { AnyView(RadarLockView(demo: false)) }),
        .init(id: "ob-symbol-assembly",
              grid: { AnyView(SymbolAssemblyView(demo: true)) },
              interactive: { AnyView(SymbolAssemblyView(demo: false)) }),
// BESPOKE-REGISTRATION-INSERT (Tools/integrate_batch.py appends above this line)
    ]

    static let gridBuilders: [String: PreviewBuilder] =
        Dictionary(all.map { ($0.id, $0.grid) }, uniquingKeysWith: { first, _ in first })

    static let interactiveBuilders: [String: PreviewBuilder] =
        Dictionary(all.map { ($0.id, $0.interactive) }, uniquingKeysWith: { first, _ in first })
}
