//
//  BespokeCodeSamples.swift
//  InspireCreativityApp
//
//  GENERATED by Tools/gen_codesamples.py — do not edit by hand.
//  Each entry is the animation view's own self-contained source, so the
//  copied code always matches the preview. Regenerate after editing views.
//

import Foundation

enum BespokeCodeSamples {
    static func code(for id: String) -> String { all[id] ?? "" }

    static let all: [String: String] = [
        "ges-rubberband-sheet-morph": ###"""
//
//  RubberBandSheetMorphView.swift
//  InspireCreativityApp — Bespoke catalog animation
//
//  Rubber-Band Sheet Morph: a bottom sheet you drag upward stretches past its
//  rest height with rubber-band resistance, and its contents re-flow from a
//  compact summary row into a multi-column grid as it rises, snapping back with
//  an overshoot spring.
//
//  Self-contained: SwiftUI only, no app dependencies (paste-and-run).
//  `demo == true`  → self-driving loop (grid tile, no finger).
//  `demo == false` → real DragGesture (Detail view + the buyer's code).
//

import SwiftUI

struct RubberBandSheetMorphView: View {
    /// Drives the self-playing demo loop in non-interactive grid tiles.
    var demo: Bool = false

    var body: some View {
        if demo {
            TimelineView(.animation) { ctx in
                SheetMorphStage(progress: Self.loopProgress(ctx.date))
            }
        } else {
            InteractiveSheetMorph()
        }
    }

    /// Eased 0→1→0 triangle wave on a ~3.6s period for the demo loop.
    static func loopProgress(_ date: Date) -> CGFloat {
        let period = 3.6
        let t = date.timeIntervalSinceReferenceDate.truncatingRemainder(dividingBy: period) / period
        let triangle = t < 0.5 ? t * 2 : (1 - t) * 2
        let eased = triangle * triangle * (3 - 2 * triangle) // smoothstep
        return CGFloat(eased)
    }
}

// MARK: - Interactive variant (real drag)

private struct InteractiveSheetMorph: View {
    @State private var progress: CGFloat = 0      // 0 collapsed … 1 expanded
    @GestureState private var dragProgress: CGFloat = 0

    var body: some View {
        GeometryReader { geo in
            let live = clampRubber(progress + dragProgress)
            SheetMorphStage(progress: live)
                .contentShape(Rectangle())
                .gesture(
                    DragGesture(minimumDistance: 0)
                        .updating($dragProgress) { value, state, _ in
                            // Upward drag (negative y) increases progress.
                            state = -value.translation.height / max(120, geo.size.height * 0.6)
                        }
                        .onEnded { value in
                            let predicted = progress - value.predictedEndTranslation.height
                                / max(120, geo.size.height * 0.6)
                            withAnimation(.snappy(duration: 0.45, extraBounce: 0.2)) {
                                progress = predicted > 0.5 ? 1 : 0
                            }
                        }
                )
        }
    }

    /// Asymptotic rubber-band clamp so it can stretch a little past 0…1.
    private func clampRubber(_ p: CGFloat) -> CGFloat {
        if p < 0 { return -0.06 * (1 - 1 / (-p * 6 + 1)) }
        if p > 1 { return 1 + 0.06 * (1 - 1 / ((p - 1) * 6 + 1)) }
        return p
    }
}

// MARK: - Shared visual (used by both demo loop and interactive)

private struct SheetMorphStage: View {
    /// May slightly exceed 0…1 for the rubber-band overshoot.
    let progress: CGFloat

    var body: some View {
        GeometryReader { geo in
            let p = min(max(progress, 0), 1)
            let minH: CGFloat = 56
            let maxH = max(minH + 40, geo.size.height * 0.92)
            let overshoot = max(0, progress - 1) * 60
            let height = minH + (maxH - minH) * p + overshoot

            ZStack {
                backdrop(p: p)
                VStack {
                    Spacer(minLength: 0)
                    sheet(width: geo.size.width, height: height, p: p)
                }
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)
        }
    }

    private func backdrop(p: CGFloat) -> some View {
        LinearGradient(
            colors: [Color(red: 0.10, green: 0.11, blue: 0.18),
                     Color(red: 0.05, green: 0.06, blue: 0.10)],
            startPoint: .top, endPoint: .bottom
        )
        .overlay(Color.black.opacity(0.35 * p)) // dim as the sheet rises
    }

    private func sheet(width: CGFloat, height: CGFloat, p: CGFloat) -> some View {
        VStack(spacing: 10) {
            Capsule()
                .fill(.white.opacity(0.35))
                .frame(width: 36, height: 5)
                .padding(.top, 8)

            ZStack {
                compactRow.opacity(Double(1 - min(p * 1.6, 1)))
                expandedGrid.opacity(Double(max(0, p * 1.6 - 0.6)))
            }
            .padding(.horizontal, 14)
            Spacer(minLength: 0)
        }
        .frame(width: width, height: height, alignment: .top)
        .background(
            RoundedRectangle(cornerRadius: 22, style: .continuous)
                .fill(Color(red: 0.13, green: 0.14, blue: 0.22))
        )
        .overlay(
            RoundedRectangle(cornerRadius: 22, style: .continuous)
                .strokeBorder(.white.opacity(0.10), lineWidth: 0.5)
        )
        .shadow(color: .black.opacity(0.4), radius: 16, y: -4)
    }

    private var compactRow: some View {
        HStack(spacing: 10) {
            RoundedRectangle(cornerRadius: 8).fill(.cyan.opacity(0.85))
                .frame(width: 34, height: 34)
            VStack(alignment: .leading, spacing: 3) {
                Capsule().fill(.white.opacity(0.8)).frame(width: 90, height: 8)
                Capsule().fill(.white.opacity(0.4)).frame(width: 56, height: 6)
            }
            Spacer()
            Image(systemName: "chevron.up").font(.system(size: 12, weight: .bold))
                .foregroundStyle(.white.opacity(0.6))
        }
    }

    private var expandedGrid: some View {
        let cols = [GridItem(.flexible(), spacing: 8), GridItem(.flexible(), spacing: 8)]
        return LazyVGrid(columns: cols, spacing: 8) {
            ForEach(0..<4, id: \.self) { i in
                RoundedRectangle(cornerRadius: 10, style: .continuous)
                    .fill([Color.cyan, .purple, .pink, .orange][i].opacity(0.8))
                    .frame(height: 34)
                    .overlay(
                        Image(systemName: ["star.fill", "bolt.fill", "heart.fill", "leaf.fill"][i])
                            .font(.system(size: 13, weight: .bold))
                            .foregroundStyle(.white)
                    )
            }
        }
    }
}

#Preview { RubberBandSheetMorphView(demo: true).frame(height: 200) }
"""###,
        "mtl-heat-mirage": ###"""
//
//  HeatMirageView.swift
//  InspireCreativityApp — Bespoke catalog animation (Metal Shaders)
//
//  Heat Mirage: pixels bend with stacked noise octaves to create rising
//  heat-shimmer, with an intensity hotspot you drag to "aim the heat". Left
//  alone, a thermal column wanders up the view.
//
//  Requires the companion `HeatMirage.metal` in the same target.
//  `demo == true`  → self-driving wandering hotspot (grid tile).
//  `demo == false` → DragGesture aims the hotspot (Detail + the buyer's code).
//

import SwiftUI

struct HeatMirageView: View {
    var demo: Bool = false
    @State private var hotspot: CGPoint = .zero
    @State private var intensity: CGFloat = 0.6

    var body: some View {
        GeometryReader { geo in
            TimelineView(.animation) { ctx in
                let time = ctx.date.timeIntervalSinceReferenceDate
                let spot = demo ? Self.wander(time, in: geo.size) : effectiveHotspot(geo.size)
                heatContent
                    .distortionEffect(
                        ShaderLibrary.heatMirage(
                            .float(Float(time.truncatingRemainder(dividingBy: 1000))),
                            .float2(Float(spot.x), Float(spot.y)),
                            .float(Float(demo ? 1.0 : intensity))
                        ),
                        maxSampleOffset: CGSize(width: 14, height: 14)
                    )
            }
            .contentShape(Rectangle())
            .gesture(
                DragGesture(minimumDistance: 0)
                    .onChanged { value in
                        guard !demo else { return }
                        hotspot = value.location
                        intensity = 1.0
                    }
                    .onEnded { _ in
                        guard !demo else { return }
                        withAnimation(.easeOut(duration: 0.8)) { intensity = 0.45 }
                    }
            )
        }
    }

    private func effectiveHotspot(_ size: CGSize) -> CGPoint {
        hotspot == .zero ? CGPoint(x: size.width / 2, y: size.height * 0.6) : hotspot
    }

    private var heatContent: some View {
        ZStack {
            LinearGradient(
                colors: [Color(red: 0.95, green: 0.55, blue: 0.12),
                         Color(red: 0.55, green: 0.10, blue: 0.20),
                         .black],
                startPoint: .top, endPoint: .bottom
            )
            VStack {
                Spacer()
                Text("HEAT")
                    .font(.system(size: 40, weight: .black, design: .rounded))
                    .foregroundStyle(.white.opacity(0.85))
                Spacer()
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    static func wander(_ t: TimeInterval, in size: CGSize) -> CGPoint {
        CGPoint(x: (sin(t * 0.5) * 0.5 + 0.5) * size.width,
                y: (cos(t * 0.37) * 0.5 + 0.5) * size.height)
    }
}

#Preview { HeatMirageView(demo: true).frame(height: 200) }


// ---- Companion Metal shader (HeatMirage.metal) ----
// Add this as a .metal file in your target:
/*
//
//  HeatMirage.metal
//  InspireCreativityApp — Bespoke catalog animation (Metal Shaders)
//
//  Companion shader for HeatMirageView. A `[[ stitchable ]]` distortion that
//  offsets each sample coordinate by summed noise octaves scrolling upward to
//  fake rising heat-shimmer, with an intensity hotspot.
//

#include <metal_stdlib>
#include <SwiftUI/SwiftUI_Metal.h>
using namespace metal;

[[ stitchable ]]
float2 heatMirage(float2 position, float time, float2 hotspot, float intensity) {
    float2 p = position;
    float wave = sin(p.y * 0.06 - time * 3.0) * 2.0
               + sin(p.y * 0.13 - time * 5.0) * 1.2
               + sin(p.x * 0.05 + time * 2.0) * 0.8;
    float d = distance(p, hotspot);
    float falloff = exp(-d * 0.004) * intensity;
    p.x += wave * (0.6 + falloff * 5.0);
    p.y -= falloff * 3.0;
    return p;
}
*/
"""###,
        "tx-shatter-glass": ###"""
//
//  GlassShatterSettleView.swift
//  InspireCreativityApp — Bespoke catalog animation
//
//  Glass Shatter Settle: the headline appears as offset angular shards that fly
//  back together from the edges, each glyph rotating and decelerating into
//  perfect alignment — like time-reversed breaking.
//
//  Uses iOS 18 `TextRenderer` for per-glyph transforms; falls back to a plain
//  fade on iOS 17. Self-contained: SwiftUI only.
//  `demo == true`  → self-driving shatter→assemble loop (grid tile).
//  `demo == false` → tap re-fires the assembly (Detail + the buyer's code).
//

import SwiftUI

struct GlassShatterSettleView: View {
    var demo: Bool = false
    @State private var assembled = false

    var body: some View {
        if #available(iOS 18.0, *) {
            modern
        } else {
            fallback
        }
    }

    @available(iOS 18.0, *)
    @ViewBuilder private var modern: some View {
        if demo {
            TimelineView(.animation) { ctx in
                shatterText(progress: Self.loopProgress(ctx.date))
            }
        } else {
            shatterText(progress: assembled ? 1 : 0)
                .contentShape(Rectangle())
                .onTapGesture { refire() }
                .onAppear { refire() }
        }
    }

    private func refire() {
        assembled = false
        withAnimation(.spring(response: 0.75, dampingFraction: 0.6)) { assembled = true }
    }

    @available(iOS 18.0, *)
    private func shatterText(progress: CGFloat) -> some View {
        ZStack {
            Color(red: 0.04, green: 0.05, blue: 0.09)
            Text("SHATTER")
                .font(.system(size: 34, weight: .heavy, design: .rounded))
                .foregroundStyle(
                    LinearGradient(colors: [.white, Color(red: 0.7, green: 0.9, blue: 1.0)],
                                   startPoint: .top, endPoint: .bottom)
                )
                .textRenderer(ShatterTextRenderer(progress: progress))
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    private var fallback: some View {
        ZStack {
            Color(red: 0.04, green: 0.05, blue: 0.09)
            Text("SHATTER")
                .font(.system(size: 34, weight: .heavy, design: .rounded))
                .foregroundStyle(.white)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    /// scatter → assemble → hold, on a ~3s loop.
    static func loopProgress(_ date: Date) -> CGFloat {
        let period = 3.0
        let t = date.timeIntervalSinceReferenceDate.truncatingRemainder(dividingBy: period) / period
        if t < 0.15 { return 0 }
        if t < 0.72 {
            let u = (t - 0.15) / 0.57
            return CGFloat(u * u * (3 - 2 * u))
        }
        return 1
    }
}

@available(iOS 18.0, *)
struct ShatterTextRenderer: TextRenderer {
    var progress: CGFloat
    var animatableData: CGFloat {
        get { progress }
        set { progress = newValue }
    }

    func draw(layout: Text.Layout, in ctx: inout GraphicsContext) {
        let scatter = 1 - max(0, min(progress, 1))
        var index = 0
        for line in layout {
            for run in line {
                for glyph in run {
                    index += 1
                    let seed = Double(index) * 12.9898
                    let dx = CGFloat(cos(seed)) * 130 * scatter
                    let dy = CGFloat(sin(seed * 1.7)) * 90 * scatter
                    let angle = Angle.degrees(cos(seed * 0.7) * 75 * Double(scatter))

                    let rect = glyph.typographicBounds.rect
                    let center = CGPoint(x: rect.midX, y: rect.midY)

                    var copy = ctx
                    copy.opacity = Double(min(1, progress * 1.5))
                    copy.translateBy(x: dx, y: dy)
                    copy.translateBy(x: center.x, y: center.y)
                    copy.rotate(by: angle)
                    copy.translateBy(x: -center.x, y: -center.y)
                    copy.draw(glyph)
                }
            }
        }
    }
}

#Preview { GlassShatterSettleView(demo: true).frame(height: 200) }
"""###,
    ]
}
