//
//  BespokeSeed.swift
//  InspireCreativityApp
//
//  Catalog metadata for the bespoke animations. `swiftCode` is pulled from the
//  generated `BespokeCodeSamples` (built from each view's own source), so the
//  copied code always matches the preview. Author/downloads/rating are derived
//  deterministically from the id so listings look real without hand-authoring.
//

import Foundation

enum BespokeSeed {

    static let bespoke: [AnimationItem] = [
        make(id: "ges-rubberband-sheet-morph", name: "Rubber-Band Sheet Morph",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "A bottom sheet you drag upward stretches past its rest height with rubber-band resistance, its contents re-flowing from a compact summary row into a multi-column layout as it rises, then snapping back with an overshoot spring."),
        make(id: "tx-shatter-glass", name: "Glass Shatter Settle",
             category: .textEffects, difficulty: .advanced, iosVersion: "18+",
             tintHex: "#04050a",
             description: "The headline appears as offset angular shards that fly back together from the edges, each glyph rotating and decelerating into perfect alignment with a brief chromatic edge-glint — like time-reversed breaking. (Requires iOS 18.)"),
        make(id: "mtl-heat-mirage", name: "Heat Mirage",
             category: .metalShaders, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#1a0500",
             description: "Pixels bend with stacked noise octaves to create rising heat-shimmer, with an intensity hotspot you drag to aim the heat. Left alone, a thermal column wanders up the view."),
                make(id: "ges-accordion-fold-list", name: "Accordion Fold Reveal",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Drag a header down and the panel below unfolds in accordion bellows, each pleat catching light differently as it expands, with the fold count tied to drag distance."),
        make(id: "ges-crumple-dismiss", name: "Crumple-to-Dismiss",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Pinch a note and it crumples inward into a wrinkled paper ball with creasing shadows, shrinking as you squeeze, then on release it tosses off-screen with a tumbling spin."),
        make(id: "ges-drag-elastic-grid-warp", name: "Elastic Grid Warp",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Drag a point on a uniform dot grid and nearby dots pull toward it with falloff, the lattice warping like a stretched fishnet and rippling back to flat on release."),
        make(id: "ges-drag-liquid-fill-tilt", name: "Tilt-Pour Liquid Gauge",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Drag to tilt a container and the liquid surface stays level to gravity, sloshing with a wobbling meniscus and trailing wave that settles when you stop tilting."),
        make(id: "ges-drag-reorder-spring", name: "Spring Reorder List",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Long-press lifts a row that tilts and casts a shadow; as you drag, other rows shove aside with damped springs and trail slightly behind the gap, settling with a soft jiggle."),
        make(id: "ges-drag-rope-bridge", name: "Sag Rope Bridge",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Drag a point along a taut rope and it sags into a catenary curve under the load, neighboring planks tilting to follow, snapping taut with a damped oscillation on release."),
        make(id: "ges-drag-spring-net", name: "Trampoline Net Drag",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Press into a mesh net and it deforms into a stretched pocket with the surrounding grid lines pulling taut; release launches a ball upward proportional to the depression depth."),
        make(id: "ges-edge-swipe-page-curl", name: "Edge-Swipe Page Curl",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Swipe from the screen edge and the page lifts and curls back like turning a leaf, the curl radius tracking finger position and revealing the next page with a soft shadow gradient on the underside."),
        make(id: "mi-bubble-wrap-pop", name: "Bubble Wrap Pop",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "A grid of glossy bubbles deflates one-by-one on tap with a quick squish-and-flatten, an auto-loop randomly popping and re-inflating them."),
        make(id: "mi-copy-shred", name: "Copy Shred-Reform",
             category: .microInteractions, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#141019",
             description: "On copy the label splits into vertical strips that shuffle and reassemble into the word Copied with a checkmark sliding in."),
        make(id: "mi-copy-vanish", name: "Copy Vanish Confirm",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "On copy, the text duplicates, lifts off, and slides into a clipboard glyph that briefly bulges to swallow it, then shows a checkmark."),
        make(id: "btn-accordion-stretch", name: "Accordion Stretch",
             category: .buttons, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#16120e",
             description: "Pinch the button to expand it into a bellows of accordion pleats that spread apart revealing nested options, collapsing back when released."),
        make(id: "btn-blinds-reveal", name: "Blinds Reveal",
             category: .buttons, difficulty: .beginner, iosVersion: "17+",
             tintHex: "#16120e",
             description: "A press rotates horizontal slats like venetian blinds, flipping from the idle label to a success state slat-by-slat with staggered timing."),
        make(id: "tr-clock-pie-wipe", name: "Clock Pie Wipe",
             category: .transitions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d1016",
             description: "An angular sweep mask drawn in Canvas rotates around the center like a clock hand, progressively unveiling the next view in a radial pie sweep."),
        make(id: "tr-column-slat-slide", name: "Column Slat Slide",
             category: .transitions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d1016",
             description: "The outgoing view is split into vertical column slats that slide off-screen at staggered speeds and offsets, the next view sliding in behind each gap."),
        make(id: "tx-confetti-letters", name: "Letter Confetti Drop",
             category: .textEffects, difficulty: .advanced, iosVersion: "18+",
             tintHex: "#04050a",
             description: "The word explodes into its individual characters which tumble and fall with gravity, bounce off the bottom edge, and then magnetically reassemble back into the word with a spring as the loop repeats."),
        make(id: "ld-bouncing-payload", name: "Bouncing Payload",
             category: .loaders, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0a1014",
             description: "A ball drops under gravity, squashes on impact with the floor and stretches at the apex, losing a little height each bounce until it auto-resets and drops again."),
        make(id: "nav-arc-fan-menu", name: "Arc Fan Menu",
             category: .navigation, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#101418",
             description: "A floating button that, on long-press, fans its child actions out along an arc with a staggered spring so each item arrives a beat after the last and overshoots before settling, then sucks them back into the button on release."),
        make(id: "ges-fling-paper-plane", name: "Paper Plane Glide",
             category: .gestures, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Fling a folded paper plane and it launches along your vector, then glides in a gentle banking descent with subtle pitch bobbing before nosing down to land."),
        make(id: "ges-fling-pinball-bumpers", name: "Pinball Fling Bumpers",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Fling a ball into a field of bumpers; each hit kicks it away with added energy and a flash-and-shrink reaction, the ball ricocheting until it loses speed."),
        make(id: "ges-fling-spinner-coast", name: "Fortune Wheel Flick",
             category: .gestures, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Flick a segmented wheel and it spins with angular momentum, a ticking flap clacking past each segment and slowing with friction until the pointer eases into a final wedge."),
        make(id: "ges-gravity-bin-toss", name: "Gravity Bin Toss",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Fling chips toward a bin and they arc under gravity, bounce off the rim or each other, and pile up with stacking collisions while overflow chips spill and settle."),
        make(id: "ges-hold-charge-burst", name: "Hold-to-Charge Burst",
             category: .gestures, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Press and hold to charge a core that pulses faster, swells, and accumulates orbiting energy rings; release fires a burst whose size scales with how long you held."),
        make(id: "ges-hold-drag-slingshot-aim", name: "Hold-Aim Trajectory Cannon",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Press and drag back from a cannon to set power and angle, a dotted predicted arc updating live; release fires a ball that follows that exact arc and bounces on landing."),
        make(id: "ges-inertial-marble-throw", name: "Inertial Marble Tray",
             category: .gestures, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Fling a marble across a bordered tray and it coasts with friction, banks off the walls with energy loss, and slowly rolls to a stop, casting a moving contact shadow."),
        make(id: "ges-jelly-drag-blob", name: "Jelly Drag Blob",
             category: .gestures, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Drag a soft blob and its trailing edge lags and stretches into a teardrop while the leading edge bulges, jiggling to a round rest shape when you stop."),
        make(id: "ges-long-press-melt", name: "Long-Press Melt Button",
             category: .gestures, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Hold a button and it softens, drooping and sagging with gooey drips forming at the bottom edge that lengthen the longer you hold, snapping back solid on release."),
        make(id: "ges-magnetic-cursor-ferrofluid", name: "Ferrofluid Magnet Pull",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Drag a magnet over a pool of dark fluid and spiky tendrils rise and lean toward it, merging and splitting as the magnet moves and slumping back flat when it leaves."),
        make(id: "ges-peel-away-card", name: "Peel-Away Sticker",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Drag a corner of a card and it peels up like a sticker with a curling lit underside and a soft drop shadow following the lifted edge, snapping flat or fully tearing free based on release velocity."),
        make(id: "ges-pinch-collapse-grid", name: "Pinch-to-Collapse Stack",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Pinching a photo grid closed makes every tile fly inward and fan-stack into a single tilted pile in the center; spreading fingers re-deals them back out across the grid with staggered timing."),
        make(id: "ges-pinch-focus-depth", name: "Pinch Depth Diorama",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Pinch on a layered scene to dolly the camera between parallax planes, foreground elements scaling and sliding faster than background while blur shifts to the focused depth."),
        make(id: "ges-pinch-origami-crane", name: "Pinch Origami Fold",
             category: .gestures, difficulty: .advanced, iosVersion: "18+",
             tintHex: "#0d0e16",
             description: "Pinch a flat square and it folds along crease lines through intermediate origami states into a standing crane, each fold catching directional light, unfolding as you spread."),
        make(id: "ges-pinch-zoom-clamp-frame", name: "Pinch-Clamp Crop Frame",
             category: .gestures, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Pinch within an image and a crop frame resists past content edges with rubber-band overscroll, the dimmed outside region springing taut when you let go beyond bounds."),
        make(id: "ges-rotate-clock-rewind", name: "Twist-to-Rewind Clock",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Rotate a clock face backward and the hands wind in reverse while a ghosted scene behind it visually un-happens, fast-forwarding when you twist the other way."),
        make(id: "ges-rotate-combination-lock", name: "Combination Safe Dial",
             category: .gestures, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Rotate a numbered safe dial back and forth; correct numbers in sequence light up and on the final entry the dial spins free, a bolt retracts, and the door eases open."),
        make(id: "ges-rotate-dial-knob", name: "Tactile Detent Dial",
             category: .gestures, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Twist a knurled dial with a rotation gesture and it clicks through evenly spaced detents, with the needle slightly overshooting each notch and a tick mark flashing as it passes."),
        make(id: "ges-rotate-gear-train", name: "Meshed Gear Train",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Rotate a drive gear and a train of meshed gears turns in correct alternating directions at ratio-scaled speeds, with a brief backlash jiggle when you reverse direction."),
        make(id: "ges-pull-to-trigger-bow", name: "Slingshot Launcher",
             category: .gestures, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Pull a projectile back against a stretching elastic band that thins and tints under tension, then release to fling it forward along the loaded vector while the band recoils with a twang wobble."),
        make(id: "ges-rotate-vinyl-scrub", name: "Vinyl Scrub Platter",
             category: .gestures, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Spin a record platter with a rotate gesture; it keeps momentum and slows by friction, and dragging against the spin scrubs it back with a pitch-bent wobble of the label art."),
        make(id: "ges-swipe-curtain-part", name: "Stage Curtain Part",
             category: .gestures, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Swipe outward and two heavy fabric curtains part with rippling folds and weighted drag, gathering at the edges with bunched pleats to reveal the content stage."),
        make(id: "ges-swipe-domino-cascade", name: "Domino Swipe Cascade",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Swipe across a row of standing tiles and they topple in sequence, each knocking the next with a slight delay and angular fall, the last one triggering an action."),
        make(id: "ges-swipe-elastic-reveal", name: "Elastic Action Reveal",
             category: .gestures, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Swiping a list row left stretches a single action button that elongates elastically; past a threshold it pops into a wide pill that springs to full width and auto-fires with haptic confirmation."),
        make(id: "ges-swipe-stack-shuffle", name: "Swipe Deck Shuffle",
             category: .gestures, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Swipe the top card off a fanned stack and the cards beneath glide up and re-fan with slight rotation jitter, the flung card tumbling away with spin proportional to swipe speed."),
        make(id: "ges-swipe-stamp-impress", name: "Swipe-Stamp Impress",
             category: .gestures, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Drag a rubber stamp down onto a surface and it presses in with a squash, leaving an ink impression that blooms outward with slight bleed where pressure was highest."),
        make(id: "ges-throw-and-catch-orbit", name: "Boomerang Toss",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Fling an object and it arcs out, decelerates, curves back along a banking return path, and lands back in the launch slot with a satisfying catch bounce."),
        make(id: "ges-two-finger-shear", name: "Two-Finger Shear Card",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Drag two fingers in opposite directions across a card to shear it into a parallelogram with a glossy skew highlight, releasing to spring back to a true rectangle with a wobble."),
        make(id: "ges-two-finger-tear-seam", name: "Two-Finger Rip Seam",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Place two fingers and pull apart to rip a panel along a stretching seam that whitens under stress before splitting into two ragged halves that recoil."),
        make(id: "ges-zipper-unzip", name: "Zipper Unseal",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Drag a zipper pull downward and interlocking teeth separate one pair at a time along the track, splitting a sealed panel open to reveal content beneath with a faint fabric flex."),
        make(id: "mi-day-night-toggle", name: "Day-Night Toggle",
             category: .microInteractions, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#141019",
             description: "A switch morphs a sun into a crescent moon by sliding a shadow disc across it while tiny stars fade in and the track gradient shifts from sky-blue to indigo."),
        make(id: "mi-dogear-bookmark", name: "Dog-Ear Bookmark",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "Tapping a card folds its top corner down into a triangular dog-ear with a soft drop shadow, peeling back up when untapped."),
        make(id: "mi-elastic-segmented", name: "Elastic Segmented Control",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "The selection pill stretches toward the tapped segment, overshooting and squashing on arrival while the active label crossfades weight."),
        make(id: "mi-emoji-fountain", name: "Emoji Fountain",
             category: .microInteractions, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#141019",
             description: "Holding a button launches a continuous arcing fountain of emoji via Canvas, each with gravity, spin, and fade, the stream thickening the longer you hold."),
        make(id: "mi-favorite-fold", name: "Folding Star Favorite",
             category: .microInteractions, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#141019",
             description: "A star favorite folds origami-style: its five points fold inward to a flat disc when off and unfold with a springy snap when favorited."),
        make(id: "mi-jelly-count-badge", name: "Jelly Count Badge",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "A notification badge gains a number that drops in from above, squashing the badge into a wobbly jelly blob that wobbles back to a circle."),
        make(id: "mi-knurled-stepper", name: "Knurled Stepper",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "A plus/minus stepper where the number sits on a knurled wheel that rotates one notch per tap with a detent bounce and a brief motion-blur smear."),
        make(id: "mi-magnetic-radio-snap", name: "Snap-Together Choice Chips",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "Selectable chips drift slightly apart at rest; the chosen chip snaps to a magnetic notch with a click-in scale pop while siblings recoil."),
        make(id: "ges-tear-receipt", name: "Tear-Off Receipt",
             category: .gestures, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#0d0e16",
             description: "Drag down on a perforated stub and it tears along a jagged dotted line with a ragged fiber edge, the torn piece falling away with a flutter as the remainder springs up."),
        make(id: "mi-magnetic-snap-toggle", name: "Magnetic Snap Toggle",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "The toggle knob is dragged and, on release, accelerates with overshoot toward the nearest end as if pulled by a magnet, the track color sweeping behind it."),
        make(id: "mi-mood-morph-rating", name: "Mood-Morph Rating",
             category: .microInteractions, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#141019",
             description: "A single face icon continuously morphs its mouth path from frown to grin as you drag the rating, eyes widening at the top score."),
        make(id: "mi-mute-morph", name: "Mute Wave Morph",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "Tapping mute collapses three animated sound waves inward into the speaker and slashes a line across it; unmuting springs the waves back out."),
        make(id: "mi-orbit-badge", name: "Orbit Badge",
             category: .microInteractions, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#141019",
             description: "When a count crosses a threshold the badge spawns a tiny dot that orbits it once with a comet trail before merging back in."),
        make(id: "mi-otp-cascade", name: "OTP Cascade Entry",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "As each code digit is entered its box flips up to reveal the number with a staggered domino delay; a wrong code shakes the whole row in unison."),
        make(id: "mi-particle-assemble-check", name: "Particle Assemble Check",
             category: .microInteractions, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#141019",
             description: "Dozens of scattered dots fly inward via Canvas and lock into the silhouette of a checkmark, the last few settling with a springy jitter."),
        make(id: "mi-password-reveal", name: "Password Reveal Flip",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "Tapping the eye toggles each masked dot flipping in sequence to reveal its character, with the eye lid blinking open or shut."),
        make(id: "mi-pin-shake-success", name: "PIN Shake-to-Success",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "PIN dots fill as you type; on success they merge into a single dot that expands into a checkmark, on failure they scatter and shake."),
        make(id: "mi-popcorn-emoji", name: "Popcorn Emoji Burst",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "Tapping pops a cluster of emoji that fire upward at staggered times with slight horizontal drift, each rotating and shrinking like popping kernels."),
        make(id: "mi-pressure-pop", name: "Pressure Pop",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "A long-press fills a radial pressure ring that, on completion, releases with a sudden scale-pop and outward shockwave puff."),
        make(id: "mi-punchout-check", name: "Punch-Out Check",
             category: .microInteractions, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#141019",
             description: "A filled chip flips and a checkmark appears as negative space punched through it, light leaking through the cut edges as the chip settles."),
        make(id: "mi-radio-ink", name: "Ink-Fill Radio",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "Selecting a radio option drops a spreading ink blot that fills the circle from the touch point, deselecting the previous one which drains away."),
        make(id: "mi-reaction-tray-roll", name: "Reaction Tray Roll",
             category: .microInteractions, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#141019",
             description: "A long-press opens a row of emoji that arc up and scale in sequence; sliding across magnifies the hovered one like a fisheye dock."),
        make(id: "mi-ribbon-drop-bookmark", name: "Ribbon Drop Bookmark",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "A ribbon unfurls downward from the top edge with a pendulum swing and a swallowtail-notched bottom, settling with a gentle sway when saved."),
        make(id: "mi-rolodex-quantity", name: "Rolodex Quantity",
             category: .microInteractions, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#141019",
             description: "A quantity picker where flicking spins a vertical cylinder of numbers with momentum and perspective curl, decelerating to snap a value to center."),
        make(id: "mi-scrubber-wave", name: "Waveform Scrubber",
             category: .microInteractions, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#141019",
             description: "Dragging a scrubber across an audio waveform parts the bars around the playhead and ripples a height-wave outward from the touch point."),
        make(id: "mi-slide-to-confirm", name: "Slide to Confirm",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "A handle is dragged along a track that fills behind it with a liquid sheen; reaching the end snaps it shut and morphs the arrow into a checkmark."),
        make(id: "mi-staggered-star-rating", name: "Staggered Star Rating",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "Dragging across stars fills them left-to-right; each newly filled star pops with a staggered spring and the selected count tints warmer as it rises."),
        make(id: "mi-stretch-pill-switch", name: "Stretch Pill Switch",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "On toggle the knob stretches into an elongated capsule mid-travel then squashes back to a circle on arrival, the track inheriting the same elastic deformation."),
        make(id: "mi-swipe-reveal-trash", name: "Swipe-Reveal Trash",
             category: .microInteractions, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#141019",
             description: "Swiping a row reveals a trash action whose lid lifts and bin mouth widens as you pull further, gulping the row inward when released past threshold."),
        make(id: "mi-tactile-counter-flip", name: "Tactile Like Counter Flip",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "A reaction count where the new digit slides up on a hinged flap from behind the old one with a split-flap snap and a tiny dust puff."),
        make(id: "mi-thumb-flip-like", name: "Thumb-Flip Like",
             category: .microInteractions, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#141019",
             description: "A thumbs-up icon does a quick 3D flip on tap, rotating from outline to filled with a knuckle-crack overshoot and a faint upward float."),
        make(id: "mi-trace-checkmark", name: "Trace Checkmark",
             category: .microInteractions, difficulty: .beginner, iosVersion: "17+",
             tintHex: "#141019",
             description: "A circle stroke draws clockwise via trim, then the checkmark path strokes on with a slight overshoot bounce and a single radial spark on completion."),
        make(id: "mi-volume-fluid", name: "Fluid Volume Fill",
             category: .microInteractions, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#141019",
             description: "Dragging a vertical volume control raises a liquid level that tilts and sloshes with the drag velocity before settling flat."),
        make(id: "btn-breath-idle", name: "Breath Idle",
             category: .buttons, difficulty: .beginner, iosVersion: "17+",
             tintHex: "#16120e",
             description: "While idle the button gently inhales and exhales with a soft scale and glow rhythm; on tap it holds its breath, then exhales into the success state."),
        make(id: "btn-conveyor-load", name: "Conveyor Load",
             category: .buttons, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#16120e",
             description: "During loading a tiny conveyor belt scrolls labeled crates across the button, dropping each into a bin until the count completes and the belt stops."),
        make(id: "btn-cube-roll", name: "Cube Roll",
             category: .buttons, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#16120e",
             description: "Tapping rolls the button as a 3D cube tumbling one face forward, each face a different state (idle, loading, success) landing with a heavy bounce."),
        make(id: "btn-domino-segment", name: "Domino Segment",
             category: .buttons, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#16120e",
             description: "A segmented control's selection knocks each segment over like a falling domino chain that cascades to the chosen option and stands the rest back up."),
        make(id: "btn-elastic-sling", name: "Elastic Sling",
             category: .buttons, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#16120e",
             description: "Drag the button backward like a slingshot; a rubber band stretches between two anchors and on release the button flings forward, snaps taut, and triggers the action."),
        make(id: "btn-ferrofluid-spike", name: "Ferrofluid Spike",
             category: .buttons, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#16120e",
             description: "On hold the button surface erupts into clustered black spikes pulled toward the touch point, collapsing back into a smooth puddle on release."),
        make(id: "btn-flip-clock-toggle", name: "Flip-Clock Toggle",
             category: .buttons, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#16120e",
             description: "A toggle flips its state like a split-flap airport display, the top half cascading down to reveal ON or OFF with a mechanical settle."),
        make(id: "btn-fuse-spark", name: "Fuse Spark",
             category: .buttons, difficulty: .advanced, iosVersion: "17+",
             tintHex: "#16120e",
             description: "A long-press lights a fuse that burns along the button's edge with a traveling spark and trailing smoke until it reaches the end and detonates the action."),
        make(id: "btn-knob-detent", name: "Knob Detent",
             category: .buttons, difficulty: .intermediate, iosVersion: "17+",
             tintHex: "#16120e",
             description: "Rotate the circular button like a hardware dial; it clicks through notched detents with a tactile micro-rotation kickback at each step until it locks on a value."),
// BESPOKE-SEED-INSERT (Tools/integrate_batch.py appends above this line)
    ]

    // MARK: - Deterministic listing factory

    private static let authors: [(String, String)] = [
        ("Yuki Tanaka", "@yuki.motion"), ("Maya Ortega", "@mortega.dev"),
        ("Kenji Saito", "@kenji.codes"), ("Aria Chen", "@aria.design"),
        ("Lena Hofstad", "@lena.swift"), ("Devon Park", "@devon.builds")
    ]

    /// All bespoke animations are Pro: the catalog's free taster is locked at
    /// exactly 20 (see `CatalogGatingTests`), so new premium content must never
    /// add to the free set. Pro price normalizes to a flat $10.
    static func make(id: String, name: String, category: Category, difficulty: Difficulty,
                     iosVersion: String, tintHex: String,
                     description: String) -> AnimationItem {
        let h = stableHash(id)
        let (author, handle) = authors[h % authors.count]
        return AnimationItem(
            id: id, name: name, category: category, difficulty: difficulty,
            iosVersion: iosVersion, isPro: true, isFeatured: false, tintHex: tintHex,
            author: author, handle: handle,
            downloads: 1_800 + (h % 18_000),
            rating: 4.5 + Double(h % 5) * 0.1,
            price: 10,
            description: description,
            swiftCode: BespokeCodeSamples.code(for: id)
        )
    }

    /// FNV-1a over the id — stable across launches (unlike `String.hashValue`).
    private static func stableHash(_ s: String) -> Int {
        var hash: UInt64 = 1_469_598_103_934_665_603
        for byte in s.utf8 { hash = (hash ^ UInt64(byte)) &* 1_099_511_628_211 }
        return Int(hash & 0x7FFF_FFFF)
    }
}
