#!/usr/bin/env python3
"""Generate BespokeCodeSamples.swift from each bespoke view's own source.

Scans Animations/Catalog/**/*.swift for a `// catalog-id: <id>` marker; the
file's source (minus internal marker comments) becomes that id's paste-ready
`swiftCode`. A `// catalog-metal: <file>.metal` marker appends the companion
shader as a comment block so the snippet is complete.

Run from repo root:  python3 Tools/gen_codesamples.py
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOG = os.path.join(ROOT, "InspireCreativityApp/Animations/Catalog")
OUT = os.path.join(CATALOG, "BespokeCodeSamples.swift")
ID_RE = re.compile(r"//\s*catalog-id:\s*(\S+)")
METAL_RE = re.compile(r"//\s*catalog-metal:\s*(\S+)")

def strip_markers(src: str) -> str:
    lines = [l for l in src.splitlines()
             if not l.strip().startswith("// catalog-id:")
             and not l.strip().startswith("// catalog-metal:")]
    return "\n".join(lines).strip() + "\n"

def collect():
    entries = {}
    for dirpath, _, files in os.walk(CATALOG):
        for fn in files:
            if not fn.endswith(".swift") or fn == "BespokeCodeSamples.swift":
                continue
            path = os.path.join(dirpath, fn)
            src = open(path, encoding="utf-8").read()
            m = ID_RE.search(src)
            if not m:
                continue
            cid = m.group(1)
            code = strip_markers(src)
            mm = METAL_RE.search(src)
            if mm:
                metal_path = os.path.join(dirpath, mm.group(1))
                if os.path.exists(metal_path):
                    metal_src = open(metal_path, encoding="utf-8").read().strip()
                    code += ("\n\n// ---- Companion Metal shader (%s) ----\n"
                             "// Add this as a .metal file in your target:\n/*\n%s\n*/\n"
                             % (mm.group(1), metal_src))
            entries[cid] = code
    return entries

def emit(entries: dict) -> str:
    # choose a raw-string delimiter that can't collide with Swift source
    delim = '###'
    for code in entries.values():
        while ('"""' + delim) in code or (delim + '"""') in code:
            delim += '#'
    out = []
    out.append("//")
    out.append("//  BespokeCodeSamples.swift")
    out.append("//  InspireCreativityApp")
    out.append("//")
    out.append("//  GENERATED by Tools/gen_codesamples.py — do not edit by hand.")
    out.append("//  Each entry is the animation view's own self-contained source, so the")
    out.append("//  copied code always matches the preview. Regenerate after editing views.")
    out.append("//")
    out.append("")
    out.append("import Foundation")
    out.append("")
    out.append("enum BespokeCodeSamples {")
    out.append("    static func code(for id: String) -> String { all[id] ?? \"\" }")
    out.append("")
    out.append("    static let all: [String: String] = [")
    for cid in sorted(entries):
        body = entries[cid].rstrip("\n")
        out.append('        "%s": %s"""' % (cid, delim))  # opening delimiter (indented)
        out.append(body)                                  # source verbatim
        out.append('"""%s,' % delim)                      # closing delimiter at column 0
    out.append("    ]")
    out.append("}")
    return "\n".join(out) + "\n"

if __name__ == "__main__":
    entries = collect()
    if not entries:
        print("no catalog-id markers found", file=sys.stderr); sys.exit(1)
    open(OUT, "w", encoding="utf-8").write(emit(entries))
    print("wrote %s with %d entries: %s" % (OUT, len(entries), ", ".join(sorted(entries))))
